webflix/config/routes.rb
Rails.application.routes.draw do

  root 'movies#index'


  #########################################################
  # The "Golden 7" for accessing the "movies" resource


  get '/movies/new' => 'movies#new', as: 'new_movie'
  post '/movies' => 'movies#create', as: 'movies'

  get '/movies' => 'movies#index'
  get '/movies/:id' => 'movies#show', as: 'movie'

  get '/movies/:id/edit' => 'movies#edit', as: 'edit_movie'
  patch '/movies/:id' => 'movies#update'

  delete '/movies/:id' => 'movies#destroy'


  #########################################################
  # The "Golden 7" for accessing the "directors" resource

  get '/directors/new' => 'directors#new', as: 'new_director'

  get '/directors' => 'directors#index', as: 'directors'
  post '/directors' => 'directors#create'

  get '/directors/:id' => 'directors#show', as: 'director'


  get '/directors/:id/edit' => 'directors#edit', as: 'edit_director'
  patch '/directors/:id' => 'directors#update'

  get '/directors/:id' => 'directors#destroy'


end

webflix/app/models/actor.rb
class Actor < ActiveRecord::Base

  has_many :movie

end

webflix/app/models/director.rb
class Director < ActiveRecord::Base

  has_many :movies

  # has_many :movies, class_name: 'Movie', foreign_key: 'director_id'

  # d = Director.first
  # d.movies()

  # def movies
  #   Movie.where(director_id: self.id)
  # end

end

webflix/app/models/movie.rb
class Movie < ActiveRecord::Base

  has_many :roles
  has_many :actors, :through => :roles

  belongs_to :director


end

webflix/app/models/role.rb
class Role < ActiveRecord::Base

  belongs_to :movie
  belongs_to :actor

end

webflix/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

webflix/app/controllers/directors_controller.rb
class DirectorsController < ApplicationController

  def index
    @directors = Director.order('name asc')
  end

  def show
    director = Director.find_by(id: params["id"])

    if director == nil
      redirect_to "/directors", notice: "Director not found."
    end
  end

  def new

  end

  def create
    director = Director.new
    director.name = params[:name]
    director.save
    redirect_to "/directors"
  end

  def edit
    @director = Director.find_by(id: params["id"])
  end

  def update
    director = Director.find_by(id: params["id"])
    director.name = params[:name]
    director.save
    redirect_to "/directors"
  end

  def destroy
    director = Movie.find_by(id: params["id"])
    director.delete
    redirect_to "/directors"
  end

end

webflix/app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  before_action :find_movie, :only => [:show, :edit, :update, :destroy]
  # before_action :find_movie, :except => [:index, :create, :new]

  def find_movie
    @movie = Movie.find_by(id: params["id"])
  end

  def index
    if params["keyword"].present?
      @movies = Movie.where("title LIKE '%#{params["keyword"]}%'")
    else
      @movies = Movie.all
    end

    @movies = @movies.order('title asc')
  end

  def show
    if @movie == nil
      redirect_to movies_url, notice: "Movie not found."
    end
  end

  def new
    @directors = Director.order('name')
  end

  def create
    movie = Movie.new
    movie.title = params[:title]
    movie.year = params[:year]
    movie.runtime = params[:runtime]
    movie.rated = params[:rated]
    movie.stars = params[:stars]
    movie.director_id = params[:director_id]
    movie.plot = params[:plot]
    movie.poster_url = params[:poster_url]
    movie.save
    redirect_to movies_url
  end

  def edit
  end

  def update
    @movie.title = params[:title]
    @movie.year = params[:year]
    @movie.runtime = params[:runtime]
    @movie.rated = params[:rated]
    @movie.stars = params[:stars]
    @movie.director_id = params[:director_id]
    @movie.plot = params[:plot]
    @movie.poster_url = params[:poster_url]
    @movie.save
    redirect_to movies_url
  end

  def destroy
    @movie.delete
    redirect_to movies_url
  end

end

webflix/app/helpers/application_helper.rb
module ApplicationHelper
end

webflix/app/views/directors/edit.html.erb
<%= form_tag "/directors/#{@director.id}", :method => 'patch' do %>

  <div>
    <label for="name">Name:</label>
    <input size="80" name="title" id="name" value="<%= @director.name %>">
  </div>

  <input type="submit" name="commit" value="Update Director">
<% end %>

webflix/app/views/directors/index.html.erb
<p><%= link_to "Add a New Director", "/directors/new" %></p>

<table class="table table-striped">
  <tr>
    <th>Name</th>
  </tr>
  <% @directors.each do |director| %>
    <tr>
      <td><%= link_to director.name, director_url(director.id) %></td>
      <td><%= link_to "Edit...", "/directors/#{director.id}/edit" %></td>
      <td><%= link_to "Delete", "/directors/#{director.id}", :method => 'delete' %></td>
    </tr>
  <% end %>

</table>

webflix/app/views/directors/new.html.erb
<%= form_tag "/directors" do %>

  <div>
    <label for="name">Director:</label>
    <input size="80" name="name" id="name" placeholder="Example: Ron Howard">
  </div>

  <input type="submit" name="commit" value="Add Director">

<% end %>

webflix/app/views/directors/show.html.erb
<h2>Director Details</h2>

<p>All we keep track of is the person's name:</p>

<h4><%= @director.name %></h4>

webflix/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Webflix</title>
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>

  <div class="container">

    <h1><%= link_to "WebFlix", "/" %>

      <small><%= link_to "Movies", '/movies' %></small>
      <small><%= link_to "Directors", '/directors' %></small>
      <small><%= link_to "Actors", '/actors' %></small>
    </h1>

    <% if notice.present? %>
      <div class="alert alert-info"%>
        <%= notice %>
      </div>
    <% end %>

    <%= yield %>

  </div>

</body>
</html>

webflix/app/views/movies/edit.html.erb
<!-- <form action="/movies/<%= @movie.id %>/update"> -->
<%= form_tag "/movies/#{@movie.id}", :method => 'patch' do %>

  <div>
    <label for="title">Title:</label>
    <input size="80" name="title" id="title" value="<%= @movie.title %>">
  </div>

  <div>
    <label for="year">Year:</label>
    <input size="4" name="year" id="year" value="<%= @movie.year %>">
  </div>

  <div>
    <label for="runtime">Runtime (minutes)</label>
    <input name="runtime" id="runtime" value="<%= @movie.runtime %>">
  </div>

  <div>
    <label for="poster_url">Link to Poster:</label>
    <input size="80" name="poster_url" value="<%= @movie.poster_url %>" id="poster_url" type="url">
  </div>

  <div>
    <label>MPAA Rated: </label>
    <select name="rated" value="<%= @movie.rated %>">
      <option>NOT RATED</option>
      <option>G</option>
      <option>PG</option>
      <option>PG-13</option>
      <option>R</option>
    </select>
  </div>

  <div>
    <label for="stars">Star Rating:</label>
    <input name="stars" value="<%= @movie.stars %>" type="number" min="1" max="10">
  </div>

  <div>
    <textarea cols="80" rows="5"><%= simple_format(@movie.plot) %></textarea>
  </div>

  <div>
    <label for="director_id">Directed By: </label>
    <select name="director_id" value="<%= @movie.director_id %>">
      <% Director.all.each do |director| %>
        <option value="<%= director.id %>">
          <%= director.name %>
        </option>
      <% end %>
    </select>
  </div>

  <input type="submit" name="commit" value="Update Movie">

<% end %>

webflix/app/views/movies/index.html.erb
<%= form_tag movies_url, :method => "get" do %>

  <%= text_field_tag :keyword %>
  <%= submit_tag "Search" %>

<% end %>

<!-- <form action="movies" method="get">
  <input name="keyword" type="text">
  <input type="submit" name="commit" value="Search">
</form>
 -->
<p><%= link_to "Add a New Movie", "/movies/new" %></p>

<p><%= @movies.count %> Movies.</p>

<table class="table table-striped">
  <tr>
    <th>Title</th>
    <th>Year</th>
    <th>Running Time</th>
    <th>Rating</th>
    <th></th>
  </tr>
  <% @movies.each do |movie| %>
    <tr>
      <td><%= link_to movie.title, movie_url(movie.id) %></td>
      <td><%= movie.year %></td>
      <td><%= movie.runtime %> minutes</td>
      <td>
        <% movie.stars.times do %>
          &#9733;
        <% end %>
        <% (10 - movie.stars).times do %>
          &#9734;
        <% end %>
      </td>
      <td><%= link_to "Edit...", "/movies/#{movie.id}/edit" %></td>
      <!-- <a href="/movies/1/delete">Delete</a> -->

      <td><%= link_to "Delete", "/movies/#{movie.id}", :method => 'delete' %></td>
    </tr>
  <% end %>

</table>

webflix/app/views/movies/new.html.erb
<%= form_tag "/movies" do %>

  <div>
    <%= label_tag :title %>
    <%= text_field_tag :title, "", placeholder: 'Example: Apollo 13' %>
    <%= select_tag ... %>
    <%= check_box_tag
    <!-- <label for="title">Title:</label>
    <input size="80" name="title" id="title" placeholder="Example: Apollo 13"> -->
  </div>

  <div>
    <label for="year">Year:</label>
    <input size="4" name="year" id="year">
  </div>

  <div>
    <label for="runtime">Runtime (minutes)</label>
    <input name="runtime" id="runtime" placeholder="Example: 118">
  </div>

  <div>
    <label for="poster_url">Link to Poster:</label>
    <input size="80" name="poster_url" id="poster_url" type="url">
  </div>

  <!-- stars: integer
  runtime: integer
  plot: text
  poster_url: string
  director_id: integer
 -->
  <div>
    <label>MPAA Rated: </label>
    <select name="rated">
      <option>NOT RATED</option>
      <option>G</option>
      <option>PG</option>
      <option>PG-13</option>
      <option>R</option>
    </select>
  </div>

  <div>
    <label for="stars">Star Rating:</label>
    <input name="stars" value="5" type="number" min="1" max="10">
  </div>

  <div>
    <textarea cols="80" rows="5" placeholder="It was a dark and stormy night...." name="plot"></textarea>
  </div>

  <div>
    <label for="director_id">Directed By: </label>
    <select name="director_id">
      <% @directors.each do |director| %>
        <option value="<%= director.id %>">
          <%= director.name %>
        </option>
      <% end %>
    </select>
  </div>

  <input type="submit" name="commit" value="Add Movie">

<% end %>

webflix/app/views/movies/show.html.erb
<h2><%= @movie.title %></h2>

<p>
  <span class="rating">Rated: <%= @movie.rated %></span>
  <%= @movie.runtime %> minutes
  <% @movie.stars.times do %>
    &#9733;
  <% end %>
  <% (10 - @movie.stars).times do %>
    &#9734;
  <% end %>

</p>

<%= image_tag @movie.poster_url %>

<h4>Directed by: <%= Director.find_by(id: @movie.director_id).name %></h4>

<p><%= @movie.plot %></p>